name: rebuild-toolchain

on:
  workflow_dispatch:
     
jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto green
        run: |
          git config --local user.email 'datong5624@gmail.com'
          git config --local user.name 'eko5624'
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "nothing commit"
          git push  
