name: build-clang-toolchain

on:
  workflow_dispatch:  
  #schedule:
  #- cron: '05 0 * * MON'  
 
jobs:
  build:
    runs-on: windows-2022
    steps: 
    - uses: msys2/setup-msys2@v2
      with:
        cache: false
        location: D:\
        install: base-devel autotools p7zip
    - name: Prepare
      run: git config --global core.autocrlf input
    - uses: actions/checkout@main     
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\clang
        key: clang-ucrt-x86_64
    
    - name: Setup Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/target-llvm-mingw-2023-12-15-ucrt-x86_64.7z
        #curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/llvm-mingw-20231128-ucrt-x86_64.7z
        7z x target*.7z -o/d && mv /d/target /d/clang
        #rm /d/clang/bin/*.pdb
        cp /c/Windows/System32/cmd.exe /d/clang/bin
