name: Build All-in-One-MPV
defaults:
  run:
    shell: D:\msys64\msys2.cmd {0}
on:
  workflow_dispatch:
    inputs:
      compiler:
        description: "Compiler"
        required: false
        default: "clang-llvm-mingw"
        type: choice
        options:
        - gcc-mcf
        - gcc-win32
        - gcc-mingw64
        - clang-mingw64
        - clang-llvm-mingw
      build_target:
        description: "Build target"
        required: false
        default: "x86_64"
        type: choice
        options:
        - x86_64
        - x86_64_v3
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:
  ffmpeg:
    needs: [libplacebo]
    runs-on: windows-latest
    env:
      COMPILER: ${{ inputs.compiler }}
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }}
    steps:
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache ${{ inputs.compiler }}-${{ inputs.build_target }} Toolchain
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: ${{ inputs.compiler }}-${{ inputs.build_target }}
    - name: Build
      run: |
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/amf-headers-dev-1.5.2-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/aom-dev-3.15.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/avisynth-dev-3.7.5-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/bzip2-dev-1.0.8-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/dav1d-dev-1.5.4-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/davs2-dev-1.7-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/ffnvcodec-dev-13.1.15.0-1-x86_64.pkg.tar.zst        
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/freetype2-dev-2_14_3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/lame-dev-4.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/lcms2-dev-2.19.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libaribcaption-dev-1.1.2-1-x86_64.pkg.tar.zst                
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libbs2b-dev-3.1.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libiconv-dev-1.19-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libjpeg-dev-3.2.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libjxl-dev-0.12.0-1-x86_64.pkg.tar.zst                
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libmodplug-dev-0.8.9.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libmysofa-dev-1.3.5-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libogg-dev-1.3.6-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libopenmpt-dev-0.8.8-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libplacebo-shared-dev-7.360.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libpng-dev-1.6.58-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libsamplerate-dev-0.2.2-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libsdl2-dev-3.4.14-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libsoxr-dev-0.1.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libspeex-dev-1.2.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libsrt-dev-1.5.7-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libssh-dev-0.12.2-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libva-dev-2.24.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libvorbis_aotuv-dev-1.3.7-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libvpl-dev-2023.4.0-1-x86_64.pkg.tar.zst         
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libvpx-dev-1.17.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libwebp-dev-1.6.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libxml2-dev-2.15.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libzimg-dev-3.0.6-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libzvbi-dev-0.2.45-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/openal-soft-dev-1.25.2-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/openssl-dev-3.6.4-1-x86_64.pkg.tar.zst        
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/opus-dev-1.6.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/rubberband-dev-4.0.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/shaderc-dev-2026.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/spirv-cross-dev-1.4.357.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/svtav1-dev-4.2.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/uavs3d-dev-1.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/vapoursynth-dev-79-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/vulkan-shared-dev-1.4.309.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/vvdec-dev-3.2.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/xxhash-dev-0.8.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/xz-dev-5.8.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/zlib-dev-2.3.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/zstd-dev-1.5.7-1-x86_64.pkg.tar.zst
        pacman -U *.zst --noconfirm
        cd ffmpeg; makepkg-${COMPILER%%-*}
    - name: Collecting logs
      if: always()
      run: |
        mkdir -p ffmpeg_logs
        cp -fr $(find ffmpeg -type f -name "*.log") ffmpeg_logs || true
        7z a logs.7z ffmpeg_logs
    - name: Uploading logs
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: ffmpeg-logs
        path: logs.7z    
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-${{ inputs.compiler }}-${{ inputs.build_target }}
        assets: ffmpeg-shared*
        fail-if-no-assets: false
        fail-if-no-release: false    
    - name: Delete Dev
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev-${{ inputs.compiler }}-${{ inputs.build_target }}
        assets: ffmpeg-shared*
        fail-if-no-assets: false
        fail-if-no-release: false 
    - name: Upload
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ffmpeg/*pkg*.xz
        tag: latest-${{ inputs.compiler }}-${{ inputs.build_target }}
        overwrite: true
        file_glob: true        
    - name: Upload Dev
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ffmpeg/*.zst
        tag: dev-${{ inputs.compiler }}-${{ inputs.build_target }}
        overwrite: true
        file_glob: true

  libplacebo:
    needs: [vulkan]
    runs-on: windows-latest
    env:
      COMPILER: ${{ inputs.compiler }}
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }}
    steps:
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache ${{ inputs.compiler }}-${{ inputs.build_target }} Toolchain
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: ${{ inputs.compiler }}-${{ inputs.build_target }}
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: '3.13'
    - name: Install python dependencies
      shell: pwsh
      run: pip install ninja Jinja2 meson
    - name: Build
      run: |
        export pypath=$(cygpath -u $pythonLocation)
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/lcms2-dev-2.19.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libjpeg-dev-3.2.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/shaderc-dev-2026.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/spirv-cross-dev-1.4.357.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/vulkan-shared-dev-1.4.309.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/xxhash-dev-0.8.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/zlib-dev-2.3.3-1-x86_64.pkg.tar.zst
        pacman -U *.zst --noconfirm 
        cd libplacebo-dev; makepkg-${COMPILER%%-*}
    - name: Release
      shell: bash
      run: |
        chmod +x ./release-dev.sh
        ./release-dev.sh libplacebo-shared-dev libplacebo-dev

  luajit2:
    runs-on: windows-latest
    env:
      COMPILER: ${{ inputs.compiler }}
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }}
    steps:
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache ${{ inputs.compiler }}-${{ inputs.build_target }} Toolchain
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: ${{ inputs.compiler }}-${{ inputs.build_target }}
    - name: Build
      run: cd luajit2; makepkg-${COMPILER%%-*}
    - name: Release
      shell: bash
      run: |
        chmod +x ./release-latest.sh ./release-dev.sh
        ./release-latest.sh luajit2-shared luajit2
        ./release-dev.sh luajit2-shared-dev luajit2    

  mpv:
    needs: [ffmpeg, libplacebo, luajit2]
    runs-on: windows-latest
    env:
      COMPILER: ${{ inputs.compiler }}
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }}
    steps:
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache ${{ inputs.compiler }}-${{ inputs.build_target }} Toolchain
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: ${{ inputs.compiler }}-${{ inputs.build_target }}
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: '3.13'
    - name: Install python dependencies
      shell: pwsh
      run: pip install meson ninja
    - name: Build
      run: |
        export pypath=$(cygpath -u $pythonLocation)
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/angle-headers-dev-1.0.772-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/avisynth-dev-3.7.5-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/bzip2-dev-1.0.8-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/ffmpeg-shared-dev-9.0.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/ffnvcodec-dev-13.1.15.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/freetype2-dev-2_14_3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/fribidi-dev-1.0.16-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/harfbuzz-dev-14.4.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/lcms2-dev-2.19.1-1-x86_64.pkg.tar.zst 
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libarchive-dev-3.8.9-1-x86_64.pkg.tar.zst       
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libass-dev-0.17.5-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libbluray-dev-1.5.0-1-x86_64.pkg.tar.zst                              
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libcaca-dev-0.99.beta20-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libdvdcss-dev-1.6.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libdvdread-dev-7.1.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libdvdnav-dev-7.0.0-1-x86_64.pkg.tar.zst        
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libiconv-dev-1.19-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libjpeg-dev-3.2.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libplacebo-shared-dev-7.360.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libpng-dev-1.6.58-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libsamplerate-dev-0.2.2-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libsdl2-dev-3.4.14-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libsixel-dev-1.10.5-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libudfread-dev-1.2.0-1-x86_64.pkg.tar.zst        
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libunibreak-dev-7_0-1-x86_64.pkg.tar.zst                       
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libxml2-dev-2.15.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libzimg-dev-3.0.6-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/luajit2-shared-dev-2.1_20260824-1-x86_64.pkg.tar.zst         
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/lzo-dev-2.10-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/openal-soft-dev-1.25.2-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/openssl-dev-3.6.4-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/mujs-dev-1.3.7-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/rubberband-dev-4.0.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/shaderc-dev-2026.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/spirv-cross-dev-1.4.357.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/subrandr-dev-1.4.0-1-x86_64.pkg.tar.zst       
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/vapoursynth-dev-79-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/vulkan-shared-dev-1.4.309.0-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/xz-dev-5.8.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/zlib-dev-2.3.3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/zstd-dev-1.5.7-1-x86_64.pkg.tar.zst
        pacman -U *.zst --noconfirm
        cd mpv; makepkg-${COMPILER%%-*}
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-${{ inputs.compiler }}-${{ inputs.build_target }}
        assets: mpv-shared*
        fail-if-no-assets: false
        fail-if-no-release: false    
    - name: Upload
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mpv/*pkg*.xz
        tag: latest-${{ inputs.compiler }}-${{ inputs.build_target }}
        overwrite: true
        file_glob: true

  package:
    needs: [mpv]
    runs-on: windows-latest
    env:
      COMPILER: ${{ inputs.compiler }}
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }}
    steps:
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache ${{ inputs.compiler }}-${{ inputs.build_target }} Toolchain
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: ${{ inputs.compiler }}-${{ inputs.build_target }}
    - name: Get mpv latest commit sha
      id: get_sha
      uses: actions/github-script@main
      with:
        script: |
          const commit = await github.rest.repos.getCommit({
            owner: 'mpv-player',
            repo: 'mpv',
            ref: `master`
          })
          core.exportVariable('sha', String(commit.data.sha)) 
    - name: Add MPV_SHORT_SHA env 
      run: echo "MPV_SHORT_SHA=`echo ${{ env.sha }}| cut -c1-7`" >> $GITHUB_ENV
    - name: Get yt-dlp latest release
      id: dlp_tag    
      uses: actions/github-script@main
      with:
        script: |
          const release = await github.rest.repos.getLatestRelease({
            owner: 'yt-dlp',
            repo: 'yt-dlp'
          })
          core.exportVariable('dlp_tag', String(release.data.tag_name))    
    - name: Setup Packages
      run: |
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest-$COMPILER-$BIT/ffmpeg-shared-9.0.1-1-x86_64.pkg.tar.xz
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest-$COMPILER-$BIT/luajit2-shared-2.1_20260824-1-x86_64.pkg.tar.xz
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest-$COMPILER-$BIT/mpv-shared-0.41.0-1-x86_64.pkg.tar.xz
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest-$COMPILER-$BIT/config-1.0-1-x86_64.pkg.tar.xz
        pacman -U *.xz --noconfirm
    - name: Zip Packages    
      run: |
        curl -OL https://github.com/yt-dlp/yt-dlp/releases/download/${{ env.dlp_tag }}/yt-dlp.exe
        mv yt-dlp.exe /opt/bin
        mv /opt/mpv/* /opt/bin
        7z a shared-mpv-$BIT-$COMPILER.7z /opt/bin/*
    - name: Release
      shell: bash
      run: |
        chmod +x ./release-package.sh
        ./release-package.sh

  vulkan:
    runs-on: windows-latest
    env:
      COMPILER: ${{ inputs.compiler }}
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }}
    steps:
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache ${{ inputs.compiler }}-${{ inputs.build_target }} Toolchain
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: ${{ inputs.compiler }}-${{ inputs.build_target }}
    - name: Build
      run: cd vulkan-dev; makepkg-${COMPILER%%-*}
    - name: Release
      shell: bash
      run: |
        ./release-dev.sh vulkan-shared-dev vulkan-dev        
