name: build-my-toolchain

on:
  workflow_dispatch:  
  #schedule:
  #- cron: '05 0 * * MON'  
 
jobs:
  build:
    runs-on: windows-2022
    steps: 
    - uses: msys2/setup-msys2@v2
      with:
        cache: false
        location: D:\
        install: base-devel autotools p7zip windows-default-manifest
    - name: Prepare
      run: git config --global core.autocrlf input
    - uses: actions/checkout@main     
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20231108_13.2.1_x64-ucrt
    
    - name: Setup Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/target-gcc-mcf-13.2.1-20231110-x64-ucrt.7z
        curl -OL https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip
        curl -L -o curl-win64-mingw.zip 'https://curl.se/windows/latest.cgi?p=win64-mingw.zip'
        7z x target-gcc-mcf*.7z -o/d && mv /d/target /d/ucrt64
        7z x ninja*.zip && mv ninja.exe /d/ucrt64/bin
        7z e -r curl*.zip -o/d/ucrt64/bin '*.exe' '*.crt'
        cp /c/Windows/System32/cmd.exe /d/ucrt64/bin
        rm /d/ucrt64/bin/pkg-config.exe
        rm /d/ucrt64/bin/x86_64-w64-mingw32-pkg-config.exe

