name: build-toolchain-lhmouse

on:
  workflow_dispatch:  
  #schedule:
  #- cron: '05 0 * * MON'  
 
jobs:
  build:
    runs-on: windows-2022
    steps: 
    - uses: msys2/setup-msys2@v2
      with:
        cache: false
        location: D:\
        install: base-devel autotools p7zip
    - name: Prepare
      run: git config --global core.autocrlf input
    - uses: actions/checkout@main     
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20240501_14.0.1_x64-ucrt
    
    - name: Setup Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        curl -OL https://gcc-mcf.lhmouse.com/mingw-w64-gcc-mcf_20240501_14.0.1_x64-ucrt_f434ce2a9f16a26268a47c074e2428cacfd85bde.7z
        7z x *.7z -o/d
        curl -L -o curl-win64-mingw.zip 'https://curl.se/windows/latest.cgi?p=win64-mingw.zip'
        7z e -r curl*.zip -o/d/ucrt64/bin '*.exe' '*.crt'
        
    - name: Make Toolchain
      shell: msys2 {0}
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd mcfgthread; PATH=/usr/bin:/opt/bin:/d/ucrt64/bin makepkg 
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}   
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        ./release-latest.sh mcfgthread mcfgthread
