name: build-toolchain

on:
  workflow_dispatch:  
  #schedule:
  #- cron: '05 0 * * MON'  
 
jobs:
  build:
    runs-on: windows-2022
    steps: 
    - name: Cache msys2
      uses: actions/cache@main
      id: msys2
      with:
        path: D:\msys64
        key: msys2
    
    - name: Cache GCC With MCF 
      uses: actions/cache@main
      id: mcf-ucrt
      with:
        path: D:\ucrt64
        key: mcf-ucrt-x86_64

    - name: Cache Clang
      uses: actions/cache@main
      id: clang-ucrt
      with:
        path: D:\clang64
        key: clang-ucrt-x86_64
    
    - name: Install msys2
      if: steps.msys2.outputs.cache-hit != 'true'
      uses: msys2/setup-msys2@v2
      with:
        cache: false
        location: D:\
        install: base-devel autotools git p7zip

    - name: Prepare
      run: git config --global core.autocrlf input
    
    - name: Checkout
      uses: actions/checkout@main

    - name: Config msys2
      if: steps.msys2.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        cp msys2-config/msys2.cmd /
        cp msys2-config/makepkg_own.conf /etc
        cp msys2-config/makepkg-own /usr/bin
        
    - name: Install GCC With MCF Toolchain
      if: steps.mcf-ucrt.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/target-gcc-mcf-latest-ucrt-x86_64.7z
        7z x target-gcc-mcf*.7z -o/d && mv /d/target /d/ucrt64

    - name: Install Clang Toolchain
      if: steps.clang-ucrt.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/target-llvm-mingw-latest-ucrt-x86_64.7z
        7z x target-llvm-mingw*.7z -o/d && mv /d/target /d/clang64
        cd /d/clang64
        cp x86_64-w64-mingw32/bin/libclang_rt.asan_dynamic-x86_64.dll lib/clang/19/lib/windows
        mv bin/x86_64-w64-mingw32-as bin/x86_64-w64-mingw32-as.exe
        mv bin/x86_64-w64-mingw32-clang bin/x86_64-w64-mingw32-clang.exe
        mv bin/x86_64-w64-mingw32-clang++ bin/x86_64-w64-mingw32-clang++.exe
        mv bin/x86_64-w64-mingw32-gcc bin/x86_64-w64-mingw32-gcc.exe
        mv bin/x86_64-w64-mingw32-g++ bin/x86_64-w64-mingw32-g++.exe
        mv bin/x86_64-w64-mingw32-c++ bin/x86_64-w64-mingw32-c++.exe
        mv bin/x86_64-w64-mingw32-ld bin/x86_64-w64-mingw32-ld.exe
        mv include x86_64-w64-mingw32
        cp bin/clang.exe bin/clang-19.exe
        cp bin/clang++.exe bin/clang++-19.exe
        cp bin/x86_64-w64-mingw32-gcc.exe bin/gcc.exe
        cp bin/x86_64-w64-mingw32-g++.exe bin/g++.exe
        cp bin/x86_64-w64-mingw32-c++.exe bin/c++.exe
        cp bin/x86_64-w64-mingw32-addr2line.exe bin/addr2line.exe
        cp bin/x86_64-w64-mingw32-ar.exe bin/ar.exe
        cp bin/x86_64-w64-mingw32-dlltool.exe bin/dlltool.exe
        cp bin/x86_64-w64-mingw32-ranlib.exe bin/ranlib.exe
        cp bin/x86_64-w64-mingw32-nm.exe bin/nm.exe
        cp bin/x86_64-w64-mingw32-objcopy.exe bin/objcopy.exe
        cp bin/x86_64-w64-mingw32-readelf.exe bin/readelf.exe
        cp bin/x86_64-w64-mingw32-strings.exe bin/strings.exe
        cp bin/x86_64-w64-mingw32-strip.exe bin/strip.exe
        cp bin/x86_64-w64-mingw32-windres.exe bin/windres.exe

