name: Cache GCC with MCF Toolchain
defaults:
  run:
    shell: D:\msys64\msys2.cmd {0}

on:
  workflow_dispatch:  
  #schedule:
  #- cron: '05 0 * * MON'  
 
jobs:
  build:
    runs-on: windows-2022
    steps: 
    - name: Cache msys2
      uses: actions/cache@main
      id: msys2
      with:
        path: D:\msys64
        key: msys2
    
    - name: Cache GCC With MCF 
      uses: actions/cache@main
      id: mcf-ucrt
      with:
        path: D:\ucrt64
        key: mcf-ucrt-x86_64
    
    - name: Install msys2
      if: steps.msys2.outputs.cache-hit != 'true'
      uses: msys2/setup-msys2@v2
      with:
        cache: false
        location: D:\
        install: base-devel autotools git p7zip

    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    
    - name: Checkout
      uses: actions/checkout@main

    - name: Config msys2
      if: steps.msys2.outputs.cache-hit != 'true'
      run: |
        cp msys2-config/msys2.cmd /
        cp msys2-config/makepkg_own.conf /etc
        cp msys2-config/makepkg-own /usr/bin
        
    - name: Install GCC With MCF Toolchain
      if: steps.mcf-ucrt.outputs.cache-hit != 'true'
      run: |
        curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/target-gcc-mcf-latest-ucrt-x86_64.7z
        7z x target-gcc-mcf*.7z -o/d && mv /d/target /d/ucrt64

