name: config

on:
  workflow_dispatch:
  
jobs:
  config:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autotools git   
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@main
    - name: Build
      shell: msys2 {0}
      run: |
        cd mpv-config; makepkg
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
        CURL_RETRIES: "--connect-timeout 60 --retry 5 --retry-delay 5"     
      shell: bash 
      run: |
        chmod +x ./release-latest.sh
        ./release-dev.latest config mpv-config
