name: dav1d

on:
  workflow_dispatch:
  
jobs:  
  dav1d:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autotools nasm git
    - uses: actions/cache@v2
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20220125_11.2.1_x64-ucrt
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: eko5624/checkout@v2
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: UCRT64
      shell: msys2 {0}
      run: | 
        pip install meson ninja
        cd /d/a/mpv-win64/mpv-win64/dav1d-dev; PATH=/d/ucrt64/bin:/c/hostedtoolcache/windows/python/3.9.10/x64/scripts:/usr/bin:/opt/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg
    - name: Delete
      uses: eko5624/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev
        assets: dav1d*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      uses: eko5624/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dav1d-dev/*.zst
        tag: dev
        overwrite: true
        file_glob: true        
