name: Delete old releases

on:
  workflow_dispatch:
     
jobs:
  prune:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 10
          delete_tags: true
          delete_tag_pattern: mpv-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
