name: Delete old releases

on:
  workflow_dispatch:
     
jobs:
  prune:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: freenet-actions/delete-old-releases@v1
        with:
          prefix: '20'  # Delete all releases starting with "develop-".
          max-age: 'P3M'      # Delete all releases older than one week.
          delete-tags: true
          token: '${{ github.token }}'
