name: libaribcaption

on:
  #schedule:
  #- cron: '03 0 * * *'
  workflow_dispatch:
      
jobs:  
  libaribcaption:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autoconf-wrapper automake-wrapper libtool git mingw-w64-x86_64-cmake mingw-w64-x86_64-make            
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@main
    #- uses: actions/cache@main
    #  id: cache
    #  with:
    #    path: D:\ucrt64
    #    key: mcf_20230307_13.0.1_x64-ucrt
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: UCRT64
        CMAKE: /mingw64/bin/cmake
        MAKE: /mingw64/bin/mingw32-make
      shell: msys2 {0}
      run: |
        curl -OL https://github.com/brechtsanders/winlibs_mingw/releases/download/13.0.1-snapshot20230402-11.0.0-ucrt-r1/winlibs-x86_64-mcf-seh-gcc-13.0.1-snapshot20230402-mingw-w64ucrt-11.0.0-r1.7z
        7z x winlibs*.7z -o/d
        cd libaribcaption-dev; PATH=/usr/bin:/opt/bin:/d/mingw64/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.BOT }}   
      shell: bash 
      run: |
        ./release-dev.sh libaribcaption-dev libaribcaption-dev
