name: libdovi

on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:  
  libdovi:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autoconf-wrapper automake-wrapper git     
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@v3

    #- name: Install Rust
    #  shell: bash
    #  run: |
    #    rm -rf /c/Users/runneradmin/.cargo
    #    curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none --no-modify-path
    #    rustup toolchain install stable-x86_64-pc-windows-gnu --profile minimal 
    #    rustup update
        
    - name: Install cargo-c
      run: |
        cargo install cargo-c --features=vendored-openssl
        
    - name: Build
      env:
        MSYSTEM: UCRT64
      shell: msys2 {0}
      run: |                  
        cd libdovi-dev; PATH=/usr/bin:/opt/bin:/c/Users/runneradmin/.cargo/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg  
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev
        assets: libdovi*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libdovi-dev/*.zst
        tag: dev
        overwrite: true
        file_glob: true 
