name: libdovi

on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:  
  libdovi:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autoconf-wrapper automake-wrapper git     
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20230224_13.0.1_x64-ucrt
    
    - name: Install Rust
      shell: bash
      run: |
        rm -rf /c/Users/runneradmin/.cargo
        curl -sSf https://sh.rustup.rs |
        sh -s -- -y --default-toolchain none
        rustup toolchain install stable-x86_64-pc-windows-gnu --profile minimal
        rustup set default-host x86_64-pc-windows-gnu     
         'C:\Users\runneradmin\.cargo\bin\rustup.exe' update
    - name: Install cargo-c
      run: |
        curl -OL https://github.com/lu-zero/cargo-c/releases/latest/download/cargo-c-windows-gnu.zip
        &'C:\Program Files\7-Zip\7z.exe' x cargo-c-windows-gnu.zip -o'C:\Users\runneradmin\.cargo\bin'
        
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: UCRT64
      shell: msys2 {0}
      run: |                  
        cd libdovi-dev; PATH=/usr/bin:/opt/bin:/d/ucrt64/bin:/c/Users/runneradmin/.cargo/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg  
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev
        assets: libdovi*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libdovi-dev/*.zst
        tag: dev
        overwrite: true
        file_glob: true 
