name: libepoxy-git

on:
  workflow_dispatch:

jobs:
  libepoxy:
    runs-on: windows-2022   
    steps:
    - uses: actions/cache@v3
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20211207_11.2.1_x64-ucrt           
    - name: Prepare
      run: git config --global core.autocrlf false     
    - uses: actions/checkout@v3
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: UCRT64
      run: |
        pip install meson ninja
        C:\msys64\usr\bin\bash -lc 'pacman -S base-devel git --noconfirm'
        C:\msys64\usr\bin\bash -lc 'cd /d/a/mpv-win64/mpv-win64/libepoxy-dev; PATH=/d/ucrt64/bin:/c/hostedtoolcache/windows/python/3.9.9/x64/scripts:/usr/bin:/opt/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg'        
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev
        assets: libepoxy*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libepoxy-dev/*.zst
        tag: dev
        overwrite: true
        file_glob: true        
