name: libjxl

on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:
  libjxl:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autoconf-wrapper automake-wrapper libtool git tree mingw-w64-x86_64-cmake mingw-w64-x86_64-make            
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@main
    #- uses: actions/cache@main
    #  id: cache
    #  with:
    #    path: D:\ucrt64
    #    key: mcf_20230307_13.0.1_x64-ucrt
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: UCRT64
        CMAKE: /mingw64/bin/cmake
        MAKE: /mingw64/bin/mingw32-make
      shell: msys2 {0}
      run: |
        curl -OL https://github.com/brechtsanders/winlibs_mingw/releases/download/13.0.1-snapshot20230402-11.0.0-ucrt-r1/winlibs-x86_64-mcf-seh-gcc-13.0.1-snapshot20230402-mingw-w64ucrt-11.0.0-r1.7z
        7z x winlibs*.7z -o/d
        cd libjxl-dev; PATH=/usr/bin:/opt/bin:/d/ucrt64/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg -p PKGBUILD-new 
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
        CURL_RETRIES: "--connect-timeout 60 --retry 5 --retry-delay 5"     
      shell: bash 
      run: |
        ./release-dev.sh libjxl-dev libjxl-dev
