name: libsixel

on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:
  libsixel:
    needs: [libjpeg, libpng]
    runs-on: windows-2022
    steps:    
    - uses: msys2/setup-msys2@v2
      with:
        cache: false
        location: D:\
        install: base-devel autoconf-wrapper automake-wrapper libtool git mingw-w64-ucrt-x86_64-pkgconf              
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@main
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20231108_13.2.1_x64-ucrt
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install python dependencies
      run: |
        pip install meson ninja                
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: UCRT64
      shell: msys2 {0}
      run: |
        pypath=$(cygpath -u $pythonLocation)
        PATH=/ucrt64/bin:/d/ucrt64/bin:$pypath:$pypath/Scripts:/usr/bin:/opt/bin
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/libjpeg-dev-3.0.1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/libpng-dev-1.6.40-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/zlib-dev-2.1.4-1-x86_64.pkg.tar.zst 
        pacman -U *.zst --noconfirm        
        cd libsixel; PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg -p PKGBUILD-new
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}    
      shell: bash 
      run: |
        ./release-dev.sh libsixel-dev libsixel