name: libsrt

on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:
  libsrt:
    runs-on: windows-2022

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        cache: false
        location: D:\
        install: base-devel autoconf-wrapper automake-wrapper libtool git           
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@main
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\clang
        key: clang-ucrt-x86_64
    - name: Setting makepkg etc
      run: |
        cp pacman-config/makepkg_clang.conf /etc
        cp pacman-config/makepkg-clang /usr/bin
    - name: Build
      run: |
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/openssl-dev-3.2.0-1-x86_64.pkg.tar.zst      
        pacman -U *.zst --noconfirm    
        cd libsrt-dev; makepkg-clang
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ./release-dev.sh libsrt-dev libsrt-dev
