name: libsrt
defaults:
  run:
    shell: D:\msys64\msys2.cmd {0}
on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:
  libsrt:
    needs: [openssl]
    runs-on: windows-2022
    steps:         
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache clang
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: clang-ucrt-x86_64
    - name: Build
      env:
        MSYSTEM: CLANG64
      run: |
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/openssl-dev-3.2.0-1-x86_64.pkg.tar.zst      
        pacman -U *.zst --noconfirm                
        cd libsrt-dev; makepkg-own -sLf  
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: ./release-dev.sh libsrt-dev libsrt-dev 
