name: libzvbi

on:
  workflow_dispatch:

jobs:
  libzvbi:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel gettext-devel autotools git     
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@main
    - name: Get HASH ENV
      run: echo "random_hash=$(cat HASH)" >> $GITHUB_ENV
      shell: bash    
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20221123_13.0.0_x64-ucrt-${{ env.random_hash }}
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: UCRT64
      shell: msys2 {0}
      run: |
        ./download-dev.sh iconv libpng
        cd libzvbi-dev; PATH=/usr/bin:/opt/bin:/d/ucrt64/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg
    - name: Delete
      uses: eko5624/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev
        assets: libzvbi*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      uses: eko5624/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libzvbi-dev/*.zst
        tag: dev
        overwrite: true
        file_glob: true
