name: package

on:
  workflow_dispatch:
    inputs:
      compiler:
        description: "Compiler"
        required: false
        default: "gcc"
        type: choice
        options:
        - gcc-mcf
        - gcc-win32
        - gcc-mingw64
        - clang-mingw64
        - clang-llvm-mingw
      build_target:
        description: "Build target"
        required: false
        default: "x86_64"
        type: choice
        options:
        - x86_64
        - x86_64_v3
  #schedule:
  #- cron: '30 0 * * MON'

jobs:    
  package:
    runs-on: windows-latest
    env:
      COMPILER: ${{ inputs.compiler }}
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }}
    steps:
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache ${{ inputs.compiler }}-${{ inputs.build_target }} Toolchain
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: ${{ inputs.compiler }}-${{ inputs.build_target }}
    - name: Get mpv latest commit sha
      id: get_sha
      uses: actions/github-script@main
      with:
        script: |
          const commit = await github.rest.repos.getCommit({
            owner: 'mpv-player',
            repo: 'mpv',
            ref: `master`
          })
          core.exportVariable('sha', String(commit.data.sha)) 
    - name: Add MPV_SHORT_SHA env 
      run: echo "MPV_SHORT_SHA=`echo ${{ env.sha }}| cut -c1-7`" >> $GITHUB_ENV
    - name: Get yt-dlp latest release
      id: dlp_tag    
      uses: actions/github-script@main
      with:
        script: |
          const release = await github.rest.repos.getLatestRelease({
            owner: 'yt-dlp',
            repo: 'yt-dlp'
          })
          core.exportVariable('dlp_tag', String(release.data.tag_name))    
    - name: Setup Packages
      run: |
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest-$COMPILER-$BIT/ffmpeg-shared-8.0.1-1-x86_64.pkg.tar.xz
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest-$COMPILER-$BIT/luajit2-shared-2.1_20260114-1-x86_64.pkg.tar.xz
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest-$COMPILER-$BIT/mpv-shared-0.41.0-1-x86_64.pkg.tar.xz
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest-$COMPILER-$BIT/config-1.0-1-x86_64.pkg.tar.xz
        pacman -U *.xz --noconfirm
    - name: Zip Packages    
      run: |
        curl -OL https://github.com/yt-dlp/yt-dlp/releases/download/${{ env.dlp_tag }}/yt-dlp.exe
        mv yt-dlp.exe /opt/bin
        mv /opt/mpv/* /opt/bin
        7z a shared-mpv-$BIT-$COMPILER.7z /opt/bin/*
    - name: Release
      shell: bash
      run: |
        chmod +x ./release-package.sh
        ./release-package.sh
