name: Pruning tags
on:
#  schedule:
#    - cron: '0 12 * * MON'
# Run monthly, at 00:00 on the 1st day of month.
  workflow_dispatch:

jobs:
  del_tags:
    runs-on: windows-2022
    env:
      GH_TOKEN: ${{ github.token }}
      CURL_RETRIES: "--connect-timeout 60 --retry 5 --retry-delay 5"   
    steps:
    - uses: actions/checkout@main
      with:
        token: ${{ secrets.BOT }}
    - name: Pruning tags
      shell: bash
      run: |
        # Keep latest 30 tags/releases
        git fetch --tags
        tag_list=($(git tag -l '2022*' | sort -r ))
        echo "$tag_list"
        old=${tag_list[@]:30}
        echo "${old[@]}"
        for tag in ${old[@]}; do
          id=$(curl -u $GITHUB_ACTOR:$GH_TOKEN $CURL_RETRIES -s -X GET -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag | jq -r '.id')
          curl -u $GITHUB_ACTOR:$GH_TOKEN $CURL_RETRIES -s -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/$id
          git tag -d $tag
        done
        git push --tags --prune https://$GITHUB_ACTOR:$GH_TOKEN@github.com/${{ github.repository }}
