name: Release
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:

jobs:
  x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: build_x86_64
        run: |
          curl -u $GITHUB_ACTOR:$GH_TOKEN \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/build-all.yml/dispatches \
            -d '{"ref":"static","inputs":{"compiler":"clang-llvm-mingw"},"inputs":{"build_target":"x86_64"}}'

  x86_64_v3:
    runs-on: ubuntu-latest
    steps:
      - name: build_x86_64_v3
        run: |
          curl -u $GITHUB_ACTOR:$GH_TOKEN \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/build-all.yml/dispatches \
            -d '{"ref":"static","inputs":{"compiler":"clang-llvm-mingw"},"inputs":{"build_target":"x86_64_v3"}}'