name: test
defaults:
  run:
    shell: D:\msys64\msys2.cmd {0}
on:
  workflow_dispatch:
    inputs:
      compiler:
        description: "Compiler"
        required: false
        default: "clang-llvm-mingw"
        type: choice
        options:
        - gcc-mcf
        - gcc-win32
        - gcc-posix
        - gcc-mingw64
        - clang-mingw64
        - clang-llvm-mingw
      build_target:
        description: "Build target"
        required: false
        default: "x86_64"
        type: choice
        options:
        - x86_64
        - x86_64_v3
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:
  libzimg:
    runs-on: windows-latest
    env:
      COMPILER: ${{ inputs.compiler }}
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }}
    steps:
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache ${{ inputs.compiler }}-${{ inputs.build_target }} Toolchain
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: ${{ inputs.compiler }}-${{ inputs.build_target }}
    - name: Build
      run: cd libzimg-dev; makepkg-${COMPILER%%-*}
    - name: Release
      shell: bash
      run: ./release-dev.sh libzimg-dev libzimg-dev