name: test
defaults:
  run:
    shell: D:\msys64\msys2.cmd {0}
on:
  workflow_dispatch:
    inputs:
      compiler:
        description: "Compiler"
        required: false
        default: "clang"
        type: choice
        options:
        - gcc
        - clang
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:
  harfbuzz:
    runs-on: windows-2022
    env:
      COMPILER: ${{ inputs.compiler }}
      GH_TOKEN: ${{ secrets.BOT }}
    steps:
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache ${{ inputs.compiler }} Toolchain
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: ${{ inputs.compiler }}-ucrt-x86_64
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: '3.13'
    - name: Build
      run: |
        export pypath=$(cygpath -u $pythonLocation)
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/freetype2-dev-2_13_3-1-x86_64.pkg.tar.zst 
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/libpng-dev-1.6.50-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/zlib-dev-2.2.5-1-x86_64.pkg.tar.zst    
        pacman -U *.zst --noconfirm         
        cd harfbuzz-dev; makepkg-$COMPILER -p PKGBUILD-new
    - name: Release
      shell: bash
      run: ./release-dev.sh harfbuzz-dev harfbuzz-dev

  libass:
    needs: [harfbuzz]
    runs-on: windows-2022
    env:
      COMPILER: ${{ inputs.compiler }}
      GH_TOKEN: ${{ secrets.BOT }}
    steps:
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache msys2
      uses: actions/cache@main
      with:
        path: D:\msys64
        key: msys2
    - name: Cache ${{ inputs.compiler }} Toolchain
      uses: actions/cache@main
      with:
        path: D:\ucrt64
        key: ${{ inputs.compiler }}-ucrt-x86_64
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: '3.13' 
    - name: Build
      run: |
        export pypath=$(cygpath -u $pythonLocation)
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/freetype2-dev-2_13_3-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/fribidi-dev-1.0.16-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/harfbuzz-dev-11.3.3-1-x86_64.pkg.tar.zst 
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/libpng-dev-1.6.50-1-x86_64.pkg.tar.zst       
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/libunibreak-dev-6_1-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/zlib-dev-2.2.5-1-x86_64.pkg.tar.zst
        pacman -U *.zst --noconfirm 
        cd libass-dev; makepkg-$COMPILER
    - name: Release
      shell: bash
      run: ./release-dev.sh libass-dev libass-dev