name: toolchain-test

on:
  workflow_dispatch:  
  #schedule:
  #- cron: '05 0 * * MON'  
 
jobs:
  build:
    runs-on: windows-2022
    steps: 
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autotools p7zip
    - name: Prepare
      run: git config --global core.autocrlf input
    - uses: actions/checkout@main     
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20230426_13.1.0_x64-ucrt
    
    - name: Setup Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        curl -OL https://github.com/eko5624/toolchain-test/releases/download/toolchain/target-gcc-with-mcf-ucrt-13.1.0.7z
        7z x *.7z -o/d
        mv /d/target /d/ucrt64
        cp /d/ucrt64/x86_64-w64-mingw32/bin/libwinpthread-1.dll /d/ucrt64/bin
        curl -L -o curl-win64-mingw.zip 'https://curl.se/windows/latest.cgi?p=win64-mingw.zip'
        7z e -r curl*.zip -o/d/ucrt64/bin '*.exe' '*.crt'
