name: toolchain-winlibs

on:
  workflow_dispatch:  
  #schedule:
  #- cron: '05 0 * * MON'  
 
jobs:
  build:
    runs-on: windows-2022
    steps: 
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autotools p7zip
    - name: Prepare
      run: git config --global core.autocrlf input
    - uses: actions/checkout@main     
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20230412_13.0.1_x64-ucrt
    
    - name: Setup Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        curl -OL https://github.com/brechtsanders/winlibs_mingw/releases/download/13.0.1-snapshot20230402-11.0.0-ucrt-r1/winlibs-x86_64-mcf-seh-gcc-13.0.1-snapshot20230402-mingw-w64ucrt-11.0.0-r1.7z
        7z x winlibs*.7z -o/d
        mv /d/mingw64 /d/ucrt64
        curl -L -o curl-win64-mingw.zip 'https://curl.se/windows/latest.cgi?p=win64-mingw.zip'
        7z e -r curl*.zip -o/d/ucrt64/bin '*.exe' '*.crt'
