name: vapoursynth

on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
  
jobs:
  vapoursynth:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autotools     
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@v3
    - name: Build
      shell: msys2 {0}
      run: |
        cd vapoursynth; makepkg
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
        CURL_RETRIES: "--connect-timeout 60 --retry 5 --retry-delay 5"     
      shell: bash 
      run: |
        chmod +x ./release-latest.sh 
        chmod +x ./release-dev.sh
        ./release-latest.sh "vapoursynth-shared" "vapoursynth"
        ./release-dev.sh "vapoursynth-shared-dev" "vapoursynth"
