name: vapoursynth

on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
  
jobs:
  vapoursynth:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autotools git     
    - name: Prepare
      run: git config --global core.autocrlf input
    - uses: actions/checkout@v3     
    - name: Get HASH ENV
      run: echo "random_hash=$(cat HASH)" >> $GITHUB_ENV
      shell: bash    
    - uses: actions/cache@v3
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20220623_12.1.1_x64-ucrt-${{ env.random_hash }}         
 
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        
    - name: Install cython
      run: |
        python -m pip install --upgrade pip
        pip install cython                 
    
    #- name: Set PKG_CONFIG_PATH
    #  run: echo "PKG_CONFIG_PATH=$pythonLocation/lib/pkgconfig" >> $GITHUB_ENV

    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: UCRT64   
      shell: msys2 {0}
      run: | 
        PATH=/d/ucrt64/bin:$pythonLocation:$pythonLocation/scripts:/usr/bin:/opt/bin
        pip3 install cython
        PKG_CONFIG_PATH=/opt/lib/pkgconfig:$pythonLocation/lib/pkgconfig:$PKG_CONFIG_PATH
        cd vapoursynth; makepkg -p PKGBUILD-static 
    - name: Delete Dev
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev
        assets: vapoursynth*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload Dev
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vapoursynth/*.zst
        tag: dev
        overwrite: true
        file_glob: true
