name: vapoursynth

on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
  
jobs:
  vapoursynth:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autotools     
    - name: Prepare
      run: git config --global core.autocrlf input
    - uses: actions/checkout@main     
    - name: Get HASH ENV
      run: echo "random_hash=$(cat HASH)" >> $GITHUB_ENV
      shell: bash    
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20220823_12.2.1_x64-ucrt-${{ env.random_hash }}
    - name: Build
      shell: msys2 {0}
      run: |
        cd vapoursynth; PATH=/usr/bin:/opt/bin:/d/ucrt64/bin PKG_CONFIG="pkg-config --static" makepkg 
    - name: Delete Dev
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev
        assets: vapoursynth*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload Dev
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vapoursynth/*.zst
        tag: dev
        overwrite: true
        file_glob: true
        
